imports:
    - { resource: ../../../../../app/config/parameters.yml }

services:
    cantiga.mailing.workspace_listener:
        class: Cantiga\MailingBundle\EventListener\WorkspaceListener
        tags:
            - { name: kernel.event_listener, event: cantiga.workspace.project, method: onProjectWorkspace }
