_forum_controller:                                                                                                                                                   
    resource: "@CantigaForumBundle/Controller/ForumController.php"                                                                                                      
    type:     annotation
