imports:
    - { resource: ../../../../../app/config/parameters.yml }

services:
    cantiga.forum.workspace_listener:
        class: Cantiga\ForumBundle\EventListener\WorkspaceListener
        tags:
            - { name: kernel.event_listener, event: cantiga.workspace.project, method: onProjectWorkspace }