cantiga_core_bundle:
    resource: "@CantigaCoreBundle/Resources/config/routing.yml"
    prefix:   /
cantiga_links_bundle:
    resource: "@CantigaLinksBundle/Resources/config/routing.yml"
    prefix:   /