_memberlist_controller:                                                                                                                                                   
    resource: "@CantigaUserBundle/Controller/MemberlistController.php"                                                                                                      
    type:     annotation
_user_profile_controller:
    resource: "@CantigaUserBundle/Controller/ProfileController.php"
    type:     annotation